<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_access_menu_model');
        $this->load->model('User_access_sub_menu_model');
    }

    function index()
    {
        $data['menu'] = $this->User_access_menu_model->get_all_user_access_menu($this->session->userdata('user_id'));
        $data['subMenu'] = $this->User_access_sub_menu_model->get_all_user_access_sub_menu($this->session->userdata('user_id'));

        $this->load->view('layouts/header');
        $this->load->view('layouts/sidebar', $data);
        $this->load->view('sections/dashboard');
        $this->load->view('layouts/footer');
    }

    function grafik_perbandingan()
    {
        $data['menu'] = $this->User_access_menu_model->get_all_user_access_menu($this->session->userdata('user_id'));
        $data['subMenu'] = $this->User_access_sub_menu_model->get_all_user_access_sub_menu($this->session->userdata('user_id'));

        //Format

        $key = [
            'x' => 'bilangan',
            'y' => array('0' => 'Jumlah','1'=>'Bukan'),
            'color' => array('0' => '#4d7cff','1'=>'#45fda5'),
        ];

        $datacoba = [
            array('2010', '78','56'),
            array('2011', '10','6'),
            array('2012', '80','56'),
            array('2013', '24','70'),
            array('2014', '57','56'),
            array('2015', '60','67'),
            array('2016', '56','89'),
            array('2017', '90','90'),
            array('2018', '80','34'),
            array('2019', '3','56'),
            array('2020', '10','90'),
        ];
        $chart['key'] = $key;
        $chart['data'] = $datacoba;
        $chart['type'] = 'morris-line-chart';
        $this->load->view('layouts/header');
        $this->load->view('layouts/sidebar', $data);
        $this->load->view('sections/chart', $chart);
        $this->load->view('layouts/footer', $chart);
    }

    function detail_pendaftar_tidak_daftar_ulang(){
        $data['menu'] = $this->User_access_menu_model->get_all_user_access_menu($this->session->userdata('user_id'));
        $data['subMenu'] = $this->User_access_sub_menu_model->get_all_user_access_sub_menu($this->session->userdata('user_id'));

        //Format

        $key = [
            'x' => 'bilangan',
            'y' => array('0' => 'Jumlah'),
            'color' => array('0' => '#4d7cff'),
        ];

        $datacoba = [
            array('2010', '78'),
            array('2011', '10'),
            array('2012', '80'),
            array('2013', '24'),
            array('2014', '57'),
            array('2015', '60'),
            array('2016', '56'),
            array('2017', '90'),
            array('2018', '80'),
            array('2019', '3'),
            array('2020', '10'),
        ];
        $chart['key'] = $key;
        $chart['data'] = $datacoba;
        $chart['type'] = 'morris-line-chart';

        $tabel = [
            'nama_jurusan' => 'Sistem Informasi',
            'TA' => [
                'data' => [
                    'tahun' => '2017/2018',
                    'data'  => [
                        'alias' => [

                        ],
                        'data' => [

                        ]
                    ]
                ],
                [
                    'tahun' => '2018/2019',
                    'data'  => []
                ],
                [
                    'tahun' => '2019/2020',
                    'data'  => []
                ],
            ]
        ];
        $this->load->view('layouts/header');
        $this->load->view('layouts/sidebar', $data);
        $this->load->view('sections/chart', $chart);
        $this->load->view('sections/accordion');
        $this->load->view('layouts/footer', $chart);
    }
}
