<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_sub_menu_access_view extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_sub_menu_access_view_model');
    } 

    /*
     * Listing of user_sub_menu_access_view
     */
    function index()
    {
        $data['user_sub_menu_access_view'] = $this->User_sub_menu_access_view_model->get_all_user_sub_menu_access_view();
        
        $data['_view'] = 'user_sub_menu_access_view/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_sub_menu_access_view
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('sub_menu_id','Sub Menu Id','required');
		$this->form_validation->set_rules('view_id','View Id','required');
		$this->form_validation->set_rules('is_active','Is Active','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'sub_menu_id' => $this->input->post('sub_menu_id'),
				'view_id' => $this->input->post('view_id'),
				'is_active' => $this->input->post('is_active'),
            );
            
            $user_sub_menu_access_view_id = $this->User_sub_menu_access_view_model->add_user_sub_menu_access_view($params);
            redirect('user_sub_menu_access_view/index');
        }
        else
        {
			$this->load->model('User_sub_menu_model');
			$data['all_user_sub_menu'] = $this->User_sub_menu_model->get_all_user_sub_menu();

			$this->load->model('User_view_model');
			$data['all_user_view'] = $this->User_view_model->get_all_user_view();
            
            $data['_view'] = 'user_sub_menu_access_view/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_sub_menu_access_view
     */
    function edit($id)
    {   
        // check if the user_sub_menu_access_view exists before trying to edit it
        $data['user_sub_menu_access_view'] = $this->User_sub_menu_access_view_model->get_user_sub_menu_access_view($id);
        
        if(isset($data['user_sub_menu_access_view']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('sub_menu_id','Sub Menu Id','required');
			$this->form_validation->set_rules('view_id','View Id','required');
			$this->form_validation->set_rules('is_active','Is Active','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'sub_menu_id' => $this->input->post('sub_menu_id'),
					'view_id' => $this->input->post('view_id'),
					'is_active' => $this->input->post('is_active'),
                );

                $this->User_sub_menu_access_view_model->update_user_sub_menu_access_view($id,$params);            
                redirect('user_sub_menu_access_view/index');
            }
            else
            {
				$this->load->model('User_sub_menu_model');
				$data['all_user_sub_menu'] = $this->User_sub_menu_model->get_all_user_sub_menu();

				$this->load->model('User_view_model');
				$data['all_user_view'] = $this->User_view_model->get_all_user_view();

                $data['_view'] = 'user_sub_menu_access_view/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_sub_menu_access_view you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_sub_menu_access_view
     */
    function remove($id)
    {
        $user_sub_menu_access_view = $this->User_sub_menu_access_view_model->get_user_sub_menu_access_view($id);

        // check if the user_sub_menu_access_view exists before trying to delete it
        if(isset($user_sub_menu_access_view['id']))
        {
            $this->User_sub_menu_access_view_model->delete_user_sub_menu_access_view($id);
            redirect('user_sub_menu_access_view/index');
        }
        else
            show_error('The user_sub_menu_access_view you are trying to delete does not exist.');
    }
    
}
