<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get menu by id
     */
    function get_menu($id)
    {
        return $this->db->get_where('menu', array('id' => $id))->row_array();
    }

    /*
     * Get all menu
     */
    function get_all_menu()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('menu')->result_array();
    }

    /*
     * function to add new menu
     */
    function add_menu($params)
    {
        $this->db->insert('menu', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update menu
     */
    function update_menu($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('menu', $params);
    }

    /*
     * function to delete menu
     */
    function delete_menu($id)
    {
        return $this->db->delete('menu', array('id' => $id));
    }
}
