<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Role_access_menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get role_access_sub_menu by id
     */
    function get_role_access_menu($id)
    {
        return $this->db->get_where('role_access_menu', array('id' => $id))->row_array();
    }

    /*
     * Get all role_access_sub_menu
     */
    function get_all_role_access_menu()
    {
        $this->db->select('*,role_access_menu.id as id');
        $this->db->join('menu', 'menu.id=role_access_menu.menu_id');
        $this->db->join('role', 'role.id=role_access_menu.role_id');
        return $this->db->get('role_access_menu')->result_array();
    }

    /*
     * function to add new role_access_sub_menu
     */
    function add_role_access_menu($params)
    {
        $this->db->insert('role_access_menu', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update role_access_menu
     */
    function update_role_access_menu($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('role_access_menu', $params);
    }

    /*
     * function to delete role_access_menu
     */
    function delete_role_access_menu($id)
    {
        return $this->db->delete('role_access_menu', array('id' => $id));
    }
}
