<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sub_menu_access_view_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get sub_menu_access_view by id
     */
    function get_sub_menu_access_view($id)
    {
        return $this->db->get_where('sub_menu_access_view', array('id' => $id))->row_array();
    }

    /*
     * Get all sub_menu_access_view
     */
    function get_all_sub_menu_access_view()
    {
        $this->db->select('*,sub_menu_access_view.id as "id"');
        $this->db->join('view', 'view.id=sub_menu_access_view.view_id');
        return $this->db->get('sub_menu_access_view')->result_array();
    }
    // function get_all_sub_menu_access_view($sub_menu_id)
    // {
    //     $this->db->select('*,sub_menu_access_view.id as "id"');
    //     $this->db->join('view', 'view.id=sub_menu_access_view.view_id');
    //     return $this->db->get_where('sub_menu_access_view', array('sub_menu_id' => $sub_menu_id))->result_array();
    // }

    /*
     * function to add new sub_menu_access_view
     */
    function add_sub_menu_access_view($params)
    {
        $this->db->insert('sub_menu_access_view', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update sub_menu_access_view
     */
    function update_sub_menu_access_view($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('sub_menu_access_view', $params);
    }

    /*
     * function to delete sub_menu_access_view
     */
    function delete_sub_menu_access_view($id)
    {
        return $this->db->delete('sub_menu_access_view', array('id' => $id));
    }
}
