<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class User_sub_menu_access_view_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get user_sub_menu_access_view by id
     */
    function get_user_sub_menu_access_view($id)
    {
        return $this->db->get_where('user_sub_menu_access_view', array('id' => $id))->row_array();
    }

    /*
     * Get all user_sub_menu_access_view
     */
    function get_all_user_sub_menu_access_view($sub_menu_id)
    {
        $this->db->join('user_view', 'user_view.id=user_sub_menu_access_view.view_id');
        return $this->db->get_where('user_sub_menu_access_view', array('sub_menu_id' => $sub_menu_id))->result_array();
    }

    /*
     * function to add new user_sub_menu_access_view
     */
    function add_user_sub_menu_access_view($params)
    {
        $this->db->insert('user_sub_menu_access_view', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update user_sub_menu_access_view
     */
    function update_user_sub_menu_access_view($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('user_sub_menu_access_view', $params);
    }

    /*
     * function to delete user_sub_menu_access_view
     */
    function delete_user_sub_menu_access_view($id)
    {
        return $this->db->delete('user_sub_menu_access_view', array('id' => $id));
    }
}
