<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_view_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_view by id
     */
    function get_user_view($id)
    {
        return $this->db->get_where('user_view',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all user_view
     */
    function get_all_user_view()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('user_view')->result_array();
    }
        
    /*
     * function to add new user_view
     */
    function add_user_view($params)
    {
        $this->db->insert('user_view',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_view
     */
    function update_user_view($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('user_view',$params);
    }
    
    /*
     * function to delete user_view
     */
    function delete_user_view($id)
    {
        return $this->db->delete('user_view',array('id'=>$id));
    }
}
