<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class User_access_sub_menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get user_access_sub_menu by id
     */
    function get_user_access_sub_menu($id)
    {
        return $this->db->get_where('user_access_sub_menu', array('id' => $id))->row_array();
    }

    /*
     * Get all user_access_sub_menu
     */
    function get_all_user_access_sub_menu($user_id)
    {
        // $this->db->select('*,user_access_sub_menu.id as "id"');  
        $this->db->join('user_sub_menu', 'user_sub_menu.id=user_access_sub_menu.sub_menu_id');
        return $this->db->get_where('user_access_sub_menu', array('user_id' => $user_id, 'is_active' => 1))->result_array();
    }

    function get_all_user_access_sub_menu_semua()
    {
        // $this->db->select('*,user_access_sub_menu.id as "id"');  
        $this->db->join('user_sub_menu', 'user_sub_menu.id=user_access_sub_menu.sub_menu_id');
        return $this->db->get_where('user_access_sub_menu', array('is_active' => 1))->result_array();
    }
    

    /*
     * function to add new user_access_sub_menu
     */
    function add_user_access_sub_menu($params)
    {
        $this->db->insert('user_access_sub_menu', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update user_access_sub_menu
     */
    function update_user_access_sub_menu($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('user_access_sub_menu', $params);
    }

    /*
     * function to delete user_access_sub_menu
     */
    function delete_user_access_sub_menu($id)
    {
        return $this->db->delete('user_access_sub_menu', array('id' => $id));
    }
}
