<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class View_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get view by id
     */
    function get_view($id)
    {
        return $this->db->get_where('view', array('id' => $id))->row_array();
    }

    /*
     * Get all view
     */
    function get_all_view()
    {
        $this->db->select('view.*,api.name,api.view_name');
        $this->db->order_by('id', 'desc');
        $this->db->join('api', 'api.id = view.api_id','left');
        return $this->db->get('view')->result_array();
    }

    /*
     * function to add new view
     */
    function add_view($params)
    {
        $this->db->insert('view', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update view
     */
    function update_view($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('view', $params);
    }

    /*
     * function to delete view
     */
    function delete_view($id)
    {
        return $this->db->delete('view', array('id' => $id));
    }
}
